// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_LnGZHBG6NJOJMrT1DqCOU3xjDSjKGvc',
    appId: '1:298037947521:web:82fa73ae687b0ee2123180',
    messagingSenderId: '298037947521',
    projectId: 'qrowd-7915d',
    authDomain: 'qrowd-7915d.firebaseapp.com',
    storageBucket: 'qrowd-7915d.firebasestorage.app',
    measurementId: 'G-7C8CXZVL0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt63X-kRD_nOYsmW4Ah_f35rJWk76VNZk',
    appId: '1:298037947521:android:14eb39f615bcca3d123180',
    messagingSenderId: '298037947521',
    projectId: 'qrowd-7915d',
    storageBucket: 'qrowd-7915d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0-4LkkHkWnaloLl091uOkJk1RbpUkp0o',
    appId: '1:298037947521:ios:762e4f393d7887d0123180',
    messagingSenderId: '298037947521',
    projectId: 'qrowd-7915d',
    storageBucket: 'qrowd-7915d.firebasestorage.app',
    iosBundleId: 'com.example.qrowd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0-4LkkHkWnaloLl091uOkJk1RbpUkp0o',
    appId: '1:298037947521:ios:762e4f393d7887d0123180',
    messagingSenderId: '298037947521',
    projectId: 'qrowd-7915d',
    storageBucket: 'qrowd-7915d.firebasestorage.app',
    iosBundleId: 'com.example.qrowd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_LnGZHBG6NJOJMrT1DqCOU3xjDSjKGvc',
    appId: '1:298037947521:web:7bd0b2b51a4bf86b123180',
    messagingSenderId: '298037947521',
    projectId: 'qrowd-7915d',
    authDomain: 'qrowd-7915d.firebaseapp.com',
    storageBucket: 'qrowd-7915d.firebasestorage.app',
    measurementId: 'G-0LPSJV6BF7',
  );
}
